AnotherStory/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'', include(('Status.urls', 'Status'), namespace='Status')),
	url(r'^Main/', include(('Main.urls', 'Main'), namespace='Main')),
    url(r'^Books/', include(('Books.urls', 'Books'), namespace='Books')),
    url(r'^Subscribe/', include(('Subscriber.urls', 'Subscriber'), namespace='Subscriber')),
    url(r'^Login/', include(('Login.urls', 'Login'), namespace='Login')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

Books/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, checkUser, getJSON, addFavorite, deleteFavorite
#url for app

app_name = 'Books'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^getJSON', getJSON, name='getJSON'),
    url(r'^checkUser', checkUser, name='checkUser'),
	url(r'^addFavorite', addFavorite, name='addFavorite'),
	url(r'^deleteFavorite', deleteFavorite, name='deleteFavorite'),
]

Login/urls.py
from django.conf.urls import url
from .views import index, logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^logout', logout, name='logout'),
]

Main/urls.py
from django.urls import path
from .views import index
#url for app

app_name = 'Main'
urlpatterns = [
    path('', index),
]

Status/urls.py
from django.conf.urls import url
from .views import index, saveStatus

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^saveStatus', saveStatus, name='saveStatus'),
]

Subscriber/urls.py
from django.conf.urls import url
from .views import index, saveSubscriber, checkEmail, showSubscriber, checkPassword, unsubscribe

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^saveSubscriber', saveSubscriber, name='saveSubscriber'),
    url(r'^checkEmail', checkEmail, name='checkEmail'),
    url(r'^showSubscriber', showSubscriber, name='showSubscriber'),
    url(r'^checkPassword', checkPassword, name='checkPassword'),
    url(r'^unsubscribe', unsubscribe, name='unsubscribe'),
]

Books/models.py
from django.db import models

# Create your models here.

Login/models.py
from django.db import models

Main/models.py
from django.db import models

# Create your models here.

Status/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
	new_status = models.CharField(max_length = 300, verbose_name="Post Something")
	date = models.DateTimeField(default=timezone.now)

Subscriber/models.py
from django.db import models

class subscriberModel(models.Model):
    name = models.CharField(max_length = 20, verbose_name='')
    email = models.EmailField(unique = True, verbose_name='')
    password = models.CharField(max_length = 20, verbose_name='')

Status/forms.py
from django import forms
from .models import Status

class Status_Form(forms.ModelForm):
	class Meta: 
		model = Status
		fields = ['new_status']
		fields_required = ['new_status']
		widgets = {
			'new_status': forms.Textarea(attrs={'class': 'form-control', 'placeholder': "What's on your mind?"})
		}

Subscriber/forms.py
from django import forms
from .models import subscriberModel
import datetime

class subscriberForm(forms.ModelForm):
    class Meta:
        model = subscriberModel
        fields = '__all__'
        fields_required = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'subscriberName', 'placeholder': "Name"}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'id': 'subscriberEmail', 'placeholder': "Email Address"}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'id': 'subscriberPassword', 
                'placeholder': "Password, minimum length of 8 alphanumeric characters"}),
        }

    passwordAgain = forms.CharField(label = '', widget = forms.PasswordInput(attrs={'class': 'form-control', 
        'id': 'subscriberPassword2', 'placeholder': "Confirm Password"}))

Books/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
from django.urls import reverse
from django.http import HttpResponseRedirect
import requests

response = {}
def index(request):
	fav_book = request.session.get('fav_book', [])
	response["fav_book"] = fav_book
	response["num_fav"] = len(fav_book)
	return render(request, 'Books.html', response)

def checkUser(request):
	login = "false";
	if request.user.is_authenticated:
		login = "true";
	return JsonResponse({"login": login})

def getJSON(request):
	bookType = request.GET.get('type', '')
	url = 'https://www.googleapis.com/books/v1/volumes?q=' + bookType
	fav_book = request.session.get('fav_book', [])
	json_data = json.loads(requests.get(url).text)
	return JsonResponse({"data": json_data, "fav_book": fav_book})

def addFavorite(request):
	bookId = request.GET.get('id', '')
	fav_book = request.session.get('fav_book', [bookId])
	if bookId not in fav_book:
		fav_book.append(bookId)
	request.session['fav_book'] = fav_book
	return JsonResponse({"num_fav": len(fav_book)})

def deleteFavorite(request):
	bookId = request.GET.get('id', '')
	fav_book = request.session['fav_book']
	fav_book.remove(bookId)
	request.session['fav_num'] = fav_book
	return JsonResponse({"num_fav": len(fav_book)})

Login/views.py
from django.shortcuts import render
from django.http import JsonResponse

def index(request):
	return render(request, 'Login.html')

def logout(request):
    request.session.flush()
    return JsonResponse({"logout": "success"})

Main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'MainPage.html')

Status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status
from .forms import Status_Form

response = {}

def index(request):
	status = Status.objects.all().order_by("-date")
	response['status'] = status
	response['form'] = Status_Form
	return render(request, 'Status.html', response)

def saveStatus(request):
	form = Status_Form(request.POST or None)
	if (request.method == "POST" and form.is_valid()):
		response['new_status'] = request.POST['new_status']
		status = Status(new_status=response['new_status'])
		status.save()
		return HttpResponseRedirect('/')
	
	return render(request, 'Status.html', {'form':form})

Subscriber/views.py
from django.shortcuts import render
from .models import subscriberModel
from .forms import subscriberForm
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.http import JsonResponse

def index(request):
	response = {}
	subscribers = subscriberModel.objects.all()
	response['subscribers'] = subscribers
	response['form'] = subscriberForm
	return render(request, 'Subscriber.html', response)

def saveSubscriber(request):
	form = subscriberForm(request.POST)
	if form.is_valid():
		form.save()
		return JsonResponse(
			{'success': True}
		)
	response = JsonResponse(
		{'success': False, 'errors': form.errors}
	)
	response.status_code = 403
	return response

def checkEmail(request):
    email = request.GET.get('email', '')
    response = {'valid' : None, 'exists': None, 'messages': []}
    try:
        validate_email(email)
    except ValidationError as error:
        response['valid'] = False
        response['messages'] = error.messages
    else:
        response['valid'] = True
        if subscriberModel.objects.filter(email=email):
            response['exists'] = True
            response['messages'] = "This email has already been registered"
        else:
            response['exists'] = False
    return JsonResponse(response)

def showSubscriber(request):
	subscribers = list(subscriberModel.objects.values("name", "email", "password").order_by("name"))
	return JsonResponse({"subscribers": subscribers})

def checkPassword(request):
	email = request.GET.get('email', '')
	subscriber = subscriberModel.objects.filter(email=email)
	password = list(subscriber.values("password"))
	return JsonResponse({"password": password})

def unsubscribe(request):
	email = request.GET.get('email', '')
	response = {'success': True}
	subscriber = subscriberModel.objects.filter(email=email)
	subscriber.delete()
	return JsonResponse(response)

Books/templates/Books.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" type="text/css" href="{% static "css/MainStyle.css" %}">{% endblock %}

{% block content %}
	<div class="Books-Title">
		<p class="P-50 text-center">Most Popular Books This Month</p>
	</div>
	{% if user.is_authenticated %}
		<div class="User-Title">
			<p class="P-30 text-center"><i class="material-icons md-3">person</i> Hello, {{ user.username }}</p>
		</div>
	{% endif %}
	<div>
		<div class="Total p-3 float-left">
			<i class="fa fa-star Checked P-30 float-left p-2"></i><p class="Total-Star P-30 float-left p-0">{{ num_fav }}</p>
		</div>
		<div class="Search-Form p-2 float-right">
		  	<div class="input-group float-right p-3">
			    <input type="text" name="bookType" class="form-control float-left" id="bookType" placeholder="Search Book" value="">
		    	<div class="input-group-btn">
		      		<button class="btn BC-P F-W" id="submitSearch">
		        		<i class="fa fa-search"></i>
		      		</button>
		    	</div>
		  	</div>
		</div>
	</div>
	<div class="table-container">
		<div class="table-responsive-sm">
			<table class="table table-hover P-20">
				<thead class="text-center">
					<tr>
						<th class="w-5 align-middle">No</th>
						<th class="w-15 align-middle">Image</th>
						<th class="w-16 align-middle">Title</th>
						<th class="w-16 align-middle">Author</th>
						<th class="w-16 align-middle">Publisher</th>
						<th class="w-16 align-middle">Published Date</th>
						<th class="w-16 align-middle">Favorite</th>
			      	</tr>
			    </thead>
			    <tbody id="booksTable" class="text-center">
			    </tbody>
			</table>
		</div>
	</div>
	<!-- Modal -->
	<div class="modal fade" id="loginModal" role="dialog">
		<div class="modal-dialog modal-dialog-centered modal">
			<div class="modal-content">
				<div class="modal-header">
					<p class="modal-title-2 P-30 F-P text-center"> Login Requirement </p>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body P-20 text-center">
					<p class="modal-body-text">You are required to login to add favorites!</p>
				</div>
				<div class="modal-footer">
					<button type="button" id="loginBtn" class="btn BC-P F-W">Log in</button>
				</div>
			</div> 
		</div>
	</div>
{% endblock content %}
{% block script %}<script src="{% static "js/Books.js" %}"" type="text/javascript"></script>{% endblock %}

Login/templates/Login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" type="text/css" href="{% static "css/MainStyle.css" %}">{% endblock %}

{% block content %}
<div class="container-fluid Login-Container h-100 w-100 BC-P">
	<div class="Login text-center">
		{% if user.is_authenticated %}
		<div class="text-center Login-Title">
	        <p class="P-50 p-5"> Log Out </p>
	    </div>
		<div class="btn GoogleBtn">
		     <a href="/../Books/logout" style="text-transform:none" class="P-20">
		         <div class="GoogleLogo float-left">
		             <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
		         </div>
		         <p class="float-right GoogleText p-0 my-0">Log Out</p>
		     </a>
		</div>
		{% else %}
		<div class="text-center Login-Title">
	        <p class="P-50 p-5"> Sign In </p>
	    </div>
		<div class="btn GoogleBtn">
		     <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none" class="P-20">
		         <div class="GoogleLogo float-left">
		             <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
		         </div>
		         <p class="float-right GoogleText p-0 my-0">Sign in with Google</p>
		     </a>
		</div>
		{% endif %}
	</div>
</div>
{% endblock content %}

Main/templates/MainPage.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" type="text/css" href="{% static "css/MainStyle.css" %}">{% endblock %}

{% block content %}
	<div class="Profile text-center BC-P h-100">
		<div class="Photo">
			<img src="{% static "img/julia.jpg" %}" alt="photo" class="ProfilePhoto Border-W">
		</div>
		<div>
			<p class="B-600 P-30 text-white">Julia Ningrum</p>
			<p class="Age P-20 B-600 text-white">18 Years Old</p>
		</div>
		<div class="Contact">
			<p class="Contact-Title d-inline-block P-20 m-0 text-white">Contact</p>
			<p class="Con P-20 m-0 text-white"><i class="fa fa-envelope"></i> Julia.ningrum@ui.ac.id</p>
			<p class="Con m-0"><a href="https://www.facebook.com/julia.winx" class="text-white P-20"><i class="fa fa-facebook-square"></i> Juliani Scarlet</a></p>
			<p class="Con m-0"><a href="https://www.instagram.com/julianiscrlt/" class="text-white P-20"><i class="fa fa-instagram"></i> julianiscrlt</a></p>
			<p class="Con m-0"><a href="https://gitlab.com/Juliani27" class="text-white P-20"><i class="fa fa-gitlab"></i> Juliani27</a></p>
		</div>
		<a class="P-15 m-0 p-0 text-center SubscribeNow" href="/../Subscribe"><u>Subscribe Now!</u></a>
	</div>
	<div class="Data float-right">
		<button class="Accordion text-left P-25 text-white BC-P border-0">Biodata</button>
			<div class="Panel">
				<p class="P-20"><i class="material-icons md-3">home</i> Jatinegara, Jakarta-Timur</p>
				<p class="P-20"><i class="material-icons md-3">cake</i> Jakarta, July 27th 2000</p>
				<p class="P-20"><i class="material-icons md-3">school</i> Computer Science - University of Indonesia</p>
				<p class="P-20"><i class="material-icons md-3" id="edu">chat</i> I Can Do It!</p>
			</div>
		<button class="Accordion text-left P-25 text-white BC-P border-0">Educational Background</button>
			<div class="Panel">
				<div class="row">
					<div class="col"><p class="P-20 font-weight-bold">2005-2008</p></div>
					<div class="col-10"><p class="P-20">SDN 11 Belitung</p></div>
				</div>
				<div class="row">
					<div class="col"><p class="P-20 font-weight-bold">2008-2011</p></div>
					<div class="col-10"><p class="P-20">SDN Rawabunga 01 Pagi</p></div>
				</div>
				<div class="row">
					<div class="col"><p class="P-20 font-weight-bold">2011-2014</p></div>
					<div class="col-10"><p class="P-20">SMPN 36 Jakarta</p></div>
				</div>
				<div class="row">
					<div class="col"><p class="P-20 font-weight-bold">2014-2017</p></div>
					<div class="col-10"><p class="P-20">SMAN 54 Jakarta</p></div>
				</div>
				<div class="row">
					<div class="col"><p class="P-20 font-weight-bold">2017-Now</p></div>
					<div class="col-10"><p class="P-20">University of Indonesia</p></div>
				</div>
			</div>
		<button class="Accordion text-left P-25 text-white BC-P border-0">Interests</button>
			<div class="Panel">
				<div class="row">
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://png.icons8.com/metro/1600/music.png" alt="music" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P">Music</p>
					</div>
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://cdn3.iconfinder.com/data/icons/black-easy/512/535112-game_512x512.png" alt="game" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P">Game</p>
					</div>
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://cdn3.iconfinder.com/data/icons/glypho-design/64/paint-brush-colors-artist-512.png" alt="art" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P">Art</p>
					</div>
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://educationatw.com/wp-content/uploads/2016/06/Languages-icon.png" alt="language" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P">Language</p>
					</div>
				</div>
				<div class="row">
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://d30y9cdsu7xlg0.cloudfront.net/png/62495-200.png" alt="coding" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P">Coding</p>
					</div>
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://cdn1.iconfinder.com/data/icons/nature-22/100/icon_leaf-leaves-double-01-512.png" alt="nature" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P">Nature</p>
					</div>
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://static.thenounproject.com/png/7433-200.png" alt="comic" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P">Comic</p>
					</div>
					<div class="col">
						<div class="Int-Icon Border-W d-block m-auto"><img src="https://static.thenounproject.com/png/21701-200.png" alt="design" class="Int-Icon-Image d-block w-75 h-75"></div>
						<p class="Int-Value text-center d-block P-30 F-P" id="ski">Design</p>
					</div>
				</div>
			</div>
		<button class="Accordion text-left P-25 text-white BC-P border-0">Skills</button>
			<div class="Panel">
				<div class="row" id="SkillRow">
					<div class="col"><p class="Ski-Value d-inline-block P-25 m-O">Music</p></div>
					<div class="col-lg-10"><div class="progress d-inline-block w-100 m-0"><div class="progress-bar progressPurple P-20" style="width:80%;">80%</div></div></div>
				</div>
				<div class="row" id="SkillRow">
					<div class="col"><p class="Ski-Value d-inline-block P-25 m-O">Java</p></div>
					<div class="col-lg-10"><div class="progress d-inline-block w-100 m-0"><div class="progress-bar progressPurple P-20" style="width:50%;">50%</div></div></div>
				</div>
				<div class="row" id="SkillRow">
					<div class="col"><p class="Ski-Value d-inline-block P-25 m-O">Leadership</p></div>
					<div class="col-lg-10"><div class="progress d-inline-block w-100 m-0"><div class="progress-bar progressPurple P-20" style="width:80%;">80%</div></div></div>
				</div>
				<div class="row" id="SkillRow">
					<div class="col"><p class="Ski-Value d-inline-block P-25 m-O">Multitasking</p></div>
					<div class="col-lg-10"><div class="progress d-inline-block w-100 m-0"><div class="progress-bar progressPurple P-20" style="width:90%;">90%</div></div></div>
				</div>
				<div class="row" id="SkillRow">
					<div class="col"><p class="Ski-Value d-inline-block P-25 m-O">Reliability</p></div>
					<div class="col-lg-10"><div class="progress d-inline-block w-100 m-0"><div class="progress-bar progressPurple P-20" style="width:95%;">95%</div></div></div>
				</div>
			</div>
		<button class="Accordion text-left P-25 text-white BC-P border-0">Recent Activites</button>
			<div class="Panel">
				<div class="Committee">
					<div class="row"><p class="Activity-Value P-30 F-P">Committes</p></div>
					<div class="row">
						<div class="col">
							<img src="{% static "img/PMB.png" %}" alt="pmb" class="Committee-Image d-block m-auto">
							<p class="Committee-Value text-center P-20">Staff Akademis PMB Fasilkom UI 2018</p>
						</div>
						<div class="col">
							<img src="{% static "img/SIWAK.png" %}" alt="siwak" class="Committee-Image d-block m-auto">
							<p class="Committee-Value text-center P-20">Staff Danus SIWAKNG 2018</p>
						</div>
					</div>
				</div>
			</div>
		<button class="Accordion text-left P-25 text-white BC-P border-0">Achievements</button>
			<div class="Panel">
				<div class="row" id="AchRow">
					<div class="col"><img src="https://static.thenounproject.com/png/18791-200.png" alt="rubic" class="Ach-Icon d-block"></div>
					<div class="col-10"><p class="Ach-Explanation P-25"> 1st Place Rubik's Cube Competition Jambore 2012</p></div>
				</div>
				<div class="row" id="AchRow">
					<div class="col"><img src="https://image.freepik.com/free-icon/kanji-character_318-37273.jpg" alt="jlpt" class="Ach-Icon d-block"></div>
					<div class="col-10"><p class="Ach-Explanation P-25"> Japanese-Language Proviciency Test N5 </p></div>
				</div>
				<div class="row" id="AchRow">
					<div class="col"><img src="https://png.icons8.com/money-bag/win8/1600" alt="treasurer" class="Ach-Icon d-block"></div>
					<div class="col-10"><p class="Ach-Explanation P-25"> Best SMAN 54 Organisation Treasurer 2015/2016 </p></div>
				</div>
				<div class="row" id="AchRow">
					<div class="col"><img src="https://static.thenounproject.com/png/14215-200.png" alt="finalist" class="Ach-Icon d-block"></div>
					<div class="col-10"><p class="Ach-Explanation P-25"> Finalist Primagama Smart Competition 2016 </p></div>
				</div>
				<div class="row" id="AchRow">
					<div class="col"><img src="https://s3.amazonaws.com/tinycards/image/130624b7f2694d8050c138bf584ec331" alt="un" class="Ach-Icon d-block" ></div>
					<div class="col-10"><p class="Ach-Explanation P-25"> 1st Place Rodoku Competition Bulan Bahasa SMAN 54 </p></div>
				</div>
			</div>
		<button class="Accordion text-left P-25 text-white BC-P border-0">Experiences</button>
			<div class="Panel">
				<div class="Experience">
					<div class="row"><p class="P-25 B-600 F-P">1. General Treasurer of Language Extracurricular (XBASS) SMAN 54</p></div>
					<div class="row"><p class="Exp-Expl P-20">(2015-2016) Responsible for organisation's general financial oversight, financial planning and budgeting, financial reporting, and record keeping. </p></div>
				</div>
				<div class="Experience">
					<div class="row"><p class="P-25 B-600 F-P">2. Latihan Dasar Kepemimpinan dan Pelantikan Anggota Baru XBASS Project Officer</p></div>
					<div class="row"><p class="Exp-Expl P-20">(2016) Provides administrative and technical skills to support the project, and working with other team members to achieve project success.</p></div>
				</div>
				<div class="Experience">
					<div class="row"><p class="P-25 B-600 F-P">3. Study Tour Bahasa Asing Secretary</p></div>
					<div class="row"><p class="Exp-Expl P-20">(2016) Maintaning project effective records and administration to support and achieve project success </p></div>
				</div>
			</div>
	</div>
{% endblock content %}

Status/templates/Status.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" type="text/css" href="{% static "css/StatusStyle.css" %}">{% endblock %}
{% block title %}Status Juli!{% endblock %}
{% block content %}
	<div class="Top">
		<div class="Hello">
			<p>Hello, Apa Kabar?</p>
		</div>
		<div class="Form">
			<div class="form-group">
				<form id="form" method="POST" action="{% url 'Status:saveStatus' %}">
					{% csrf_token %}
		        	{{ form.as_p}}
					<button type="submit" class="btn btn-danger" id="submit"><i class="fa fa-pencil"></i></button>
				</form>
			</div>
		</div>
	</div>
	<div class="Bottom">
		<div class="Posts-Title">
			<p>Recent Posts</p>
		</div>
		{% if status %}
		<div class="Status-Container">
			{% for data in status %}
			<div class="My-Status">
				<div class="Photo">
					<img src="{% static "img/julia.jpg" %}" alt="photo" class="Profile-Photo">
				</div>
				<div class="Post float-left">
					<div class="row m-0">
						<div class="col p-0">
							<p class="Name m-0 p-0 font-weight-bold">Julia Ningrum</p>
						</div>
						<div class="col p-0">
							<p class="Date m-0 p-0 float-right">{{ data.date|date:"M d, Y" }} at {{ data.date|time:"H:i"}}</p>
						</div>
					</div>
					<div class="row m-0">
						<p class="New-Post m-0 p-0 float-left">{{ data.new_status }}</p>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% else %}
			<div class="No-Status">
				<p class="m-0 p-0">Add your first status!</p>
			</div>
		{% endif %}
	</div>
{% endblock content %}